/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym_zarate;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author soner
 */
public class Marcas extends javax.swing.JInternalFrame {

    String ar1[]={"Marcas"};
String ar2[][]=new String [1][1];
    /**
     * Creates new form Marcas
     */
    public Marcas() {
        initComponents();
        Txt_Marca.requestFocus();
    }
public String[][] llenarArreglo2(){
        String temp[][]=new String [1][1];
        try{
            //last() envia al final de la tabla
            //previous() se va al anterior
            //first se va al princicipo

              Connection cn = Conexion.conecta("brenda", "sasa", "gym_zarate");
            Statement st= cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);//scroll hace que te muevas a la posicion que desees
            ResultSet rs=st.executeQuery("select *from marcas where Descripcion !='';");
            if(rs.last());
            int filas=rs.getRow();
            temp=new String[filas][5];
            rs.first();
            for(int i = 0; i< temp.length; i++){
                temp[i][0]=rs.getString("Descripcion");
                rs.next();
            }
            return temp;
        }catch(Exception e){
            System.out.print(e);
            return temp;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Txt_Marca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        setClosable(true);
        setIconifiable(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Marcas.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nombre_marca.png"))); // NOI18N

        Txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MarcaActionPerformed(evt);
            }
        });
        Txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_MarcaKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marcas"
            }
        ));
        jScrollPane1.setViewportView(Lista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

  if(Txt_Marca.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null,"Campo vacio, Coloca una marca");
    ar2=llenarArreglo2();
    Lista=new JTable (ar2,ar1);
    jScrollPane1.setViewportView(Lista);
    
}
else
{
    String Marca="";
        try{
           
Marca = Txt_Marca.getText().toString().toUpperCase();

            Connection cn = Conexion.conecta("brenda", "sasa", "gym_zarate");
         PreparedStatement st = cn.prepareStatement("INSERT INTO Marcas(Descripcion) SELECT '"+Marca+"' FROM Marcas WHERE NOT EXISTS (SELECT Descripcion FROM Marcas WHERE Descripcion = '"+Marca+"')LIMIT 1;");
           
            st.execute();
          
           JOptionPane.showMessageDialog(null, "Marca "+Marca+" Agregada exitosamente");
           Txt_Marca.setText("");
           Txt_Marca.requestFocus();
           
           
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
            
        }    
         ar2=llenarArreglo2();
        Lista=new JTable (ar2,ar1);
        jScrollPane1.setViewportView(Lista);
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_MarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_MarcaKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MarcaKeyPressed

    private void Txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MarcaActionPerformed
if(Txt_Marca.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null,"Campo vacio, Coloca una marca");
    ar2=llenarArreglo2();
    Lista=new JTable (ar2,ar1);
    jScrollPane1.setViewportView(Lista);
    
}
else
{
    String Marca="";
        try{
           
Marca = Txt_Marca.getText().toString().toUpperCase();

            Connection cn = Conexion.conecta("brenda", "sasa", "gym_zarate");
         PreparedStatement st = cn.prepareStatement("INSERT INTO Marcas(Descripcion) SELECT '"+Marca+"' FROM Marcas WHERE NOT EXISTS (SELECT Descripcion FROM Marcas WHERE Descripcion = '"+Marca+"')LIMIT 1;");
           
            st.execute();
          
           JOptionPane.showMessageDialog(null, "Marca "+Marca+" Agregada exitosamente");
           Txt_Marca.setText("");
           Txt_Marca.requestFocus();
           
           
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
            
        }    
         ar2=llenarArreglo2();
        Lista=new JTable (ar2,ar1);
        jScrollPane1.setViewportView(Lista);
}
        
               // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MarcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Lista;
    private javax.swing.JTextField Txt_Marca;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
