/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gym_zarate;

import conexion.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Types;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author soner
 */
public class Nuevo_Producto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nuevo_Producto
     */
    public Nuevo_Producto() {
        initComponents();
        ListarCombo();
        AutoCompleteDecorator.decorate(Cbx_Marca);
    }
    String ar1[]={"PRODUCTO","MARCA","TALLA","EXISTENCIA","TIPO","$ CLIENTE","$ COMPRA"};
String ar2[][]=new String [1][7];
     private void ListarCombo() {
        try {
            Connection c = Conexion.conecta("brenda", "sasa", "pacifico");
            Cbx_Marca = Conexion.llenarCombo("select Descripcion from Marcas where Descripcion !=''", Cbx_Marca);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     public String[][] llenarArreglo2(){
        String temp[][]=new String [1][7];
        try{
            //last() envia al final de la tabla
            //previous() se va al anterior
            //first se va al princicipo

              Connection cn = Conexion.conecta("brenda", "sasa", "gym_zarate");
            Statement st= cn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);//scroll hace que te muevas a la posicion que desees
            ResultSet rs=st.executeQuery("select x.Descripcion, y.Descripcion, x.talla, x.existencia, x.Tipo_Producto,x.Costo_Cliente, x.Costo_Compra from productos x, marcas y where x.Id_Marca = y.Id_Marca;");
            if(rs.last());
            int filas=rs.getRow();
            temp=new String[filas][7];
            rs.first();
            for(int i = 0; i< temp.length; i++){
                temp[i][0]=rs.getString("X.Descripcion");
                temp[i][1]=rs.getString("Y.Descripcion");
                temp[i][2]=rs.getString("x.talla");
                temp[i][3]=rs.getString("x.existencia");
                temp[i][4]=rs.getString("x.tipo_producto");
                temp[i][5]=rs.getString("x.Costo_Cliente");
                temp[i][6]=rs.getString("x.Costo_Compra");
                rs.next();
            }
            return temp;
        }catch(Exception e){
            System.out.print(e);
            return temp;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Txt_Descripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cbx_Marca = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Txt_Talla = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_Extencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Cbx_Tipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Txt_Compra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_Cliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Productos.png"))); // NOI18N

        Txt_Descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_Descripcion.setForeground(new java.awt.Color(0, 0, 204));
        Txt_Descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_DescripcionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Descripcion");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Marca");

        Cbx_Marca.setEditable(true);
        Cbx_Marca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cbx_Marca.setForeground(new java.awt.Color(0, 0, 204));
        Cbx_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbx_MarcaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Talla");

        Txt_Talla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_Talla.setForeground(new java.awt.Color(0, 0, 204));
        Txt_Talla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TallaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("$ Cliente");

        Txt_Extencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_Extencia.setForeground(new java.awt.Color(0, 0, 204));
        Txt_Extencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ExtenciaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Tipo");

        Cbx_Tipo.setEditable(true);
        Cbx_Tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cbx_Tipo.setForeground(new java.awt.Color(0, 0, 204));
        Cbx_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa", "Cafeteria", "Suplementos", "" }));
        Cbx_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbx_TipoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 204));
        jLabel8.setText("Existencia");

        Txt_Compra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_Compra.setForeground(new java.awt.Color(0, 0, 204));
        Txt_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_CompraActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("$ Compra");

        Txt_Cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Txt_Cliente.setForeground(new java.awt.Color(0, 0, 204));
        Txt_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ClienteActionPerformed(evt);
            }
        });

        Lista.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Lista.setForeground(new java.awt.Color(0, 0, 204));
        Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Marca", "Talla", "Existencia", "Tipo", "Costo Cliente", "Costo Compra"
            }
        ));
        jScrollPane1.setViewportView(Lista);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_Extencia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cbx_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Txt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Cbx_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(Txt_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5)
                                .addGap(37, 37, 37)
                                .addComponent(Txt_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Cbx_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_Talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Extencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(Cbx_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Txt_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_DescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_DescripcionActionPerformed
Cbx_Marca.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_Txt_DescripcionActionPerformed

    private void Cbx_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbx_MarcaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_Cbx_MarcaActionPerformed

    private void Txt_TallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TallaActionPerformed
Txt_Extencia.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TallaActionPerformed

    private void Txt_ExtenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ExtenciaActionPerformed
Cbx_Tipo.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ExtenciaActionPerformed

    private void Cbx_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbx_TipoActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Cbx_TipoActionPerformed

    private void Txt_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ClienteActionPerformed
Txt_Compra.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ClienteActionPerformed

    private void Txt_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_CompraActionPerformed
if(Txt_Cliente.getText().isEmpty() || Txt_Descripcion.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null,"Campo vacio, Ingresa datos");
  
       ar2=llenarArreglo2();
        Lista=new JTable (ar2,ar1);
        jScrollPane1.setViewportView(Lista);
}
else
{
    String Marca="";
        try{
           


            Connection cn = Conexion.conecta("brenda", "sasa", "gym_zarate");
      CallableStatement cs = cn.prepareCall("Call AddProducto(?,?,?,?,?,?,?,?)");
                cs.setString(1,Txt_Descripcion.getText().toString().toUpperCase());
                cs.setString(2,Cbx_Marca.getSelectedItem().toString());
                cs.setString(3,Txt_Talla.getText().toString().toUpperCase());
                cs.setDouble(4,Double.parseDouble(Txt_Extencia.getText()));
                String Tipo_Producto = "";
                Tipo_Producto = Cbx_Tipo.getSelectedItem().toString();
                
                if(Tipo_Producto.equals("Ropa"))
                {
                    cs.setString(5,"R");
                }
                else if(Tipo_Producto.equals("Cafeteria"))
                {
                     cs.setString(5,"C");
                }
                else if(Tipo_Producto.equals("Suplementos"))
                {
                     cs.setString(5,"S");
                }
                 cs.setDouble(6,Double.parseDouble(Txt_Cliente.getText()));
                 cs.setDouble(7,Double.parseDouble(Txt_Compra.getText()));
                cs.registerOutParameter(8,Types.INTEGER);
                cs.execute();
                int es=cs.getInt(8);
                
               if(es==1){
                JOptionPane.showMessageDialog(null,"Producto agregado exitosamente");
                
               }
               else{
                   JOptionPane.showMessageDialog(null,"Error");
               }
           
           
        }catch(Exception e){
          JOptionPane.showMessageDialog(null, e);
            
        }    
         ar2=llenarArreglo2();
        Lista=new JTable (ar2,ar1);
        jScrollPane1.setViewportView(Lista);
}
 
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_CompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbx_Marca;
    private javax.swing.JComboBox<String> Cbx_Tipo;
    private javax.swing.JTable Lista;
    private javax.swing.JTextField Txt_Cliente;
    private javax.swing.JTextField Txt_Compra;
    private javax.swing.JTextField Txt_Descripcion;
    private javax.swing.JTextField Txt_Extencia;
    private javax.swing.JTextField Txt_Talla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
